docker run --name diflix-postgres \
  -e POSTGRES_USER=postgres \
  -e POSTGRES_PASSWORD=1234 \
  -e POSTGRES_DB=diflixdb \
  -p 5432:5432 \
  -v diflix_pgdata:/var/lib/postgresql/data \
  --restart always \
  -d postgres:15
