version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: diflix-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: diflixdb
    ports:
      - "5432:5432"
    volumes:
      - diflixdb_data:/var/lib/postgresql/data

volumes:
  diflixdb_data:
