version: "3.8"

services:
  frontend:
    build:
      context: ../frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build:
      context: ../backend
    ports:
      - "4000:4000"
    env_file:
      - ../backend/.env
    environment:
      - DATABASE_URL=postgresql://postgres:1111@db:5432/diflixdb
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=diflixdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
